version: '3.7'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Test@1234
      MYSQL_DATABASE: chatapp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - chatapp
  app:
    image: sidraut007/chatapp
    container_name: chatapp
    environment:
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Test@1234"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/chatapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    volumes:
      - ./app:/app
    ports:
      - "8081:8080"
    command: ["java", "-jar", "/src/target/chatapp.jar"]
    networks:
      - chatapp
    depends_on:
      - db
    restart: always
networks:
  chatapp:
    name: chatapp
    driver: bridge

volumes:
  db_data:

