apiVersion: v1
kind: Service
metadata:
  name: chatapp-service
  labels:
    app: chatapp
spec:
  selector:
    app: chatapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP